swagger: "2.0"
info:
  description: Nolja API
  version: 1.0.0
  title: Swagger Nolja
  contact:
    email: nguyenbrother9x@gmail.com
tags:
  - name: user
    description: Everything about your User
schemes:
  - https
  - http

paths:
  /api/v1/users/me:
    get:
      tags:
        - user
      summary: Get Current logged-in user info
      description: Return user info with preference/setting
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: header
          name: Authorization
          type: string
          required: true
      responses:
        "200":
          description: On success
          schema:
            type: object
            required:
              - code
              - message
            properties:
              code:
                type: integer
                format: int32
                example: 0
              message:
                type: string
                example: success
              data:
                $ref: "#/definitions/User"
    put:
      tags:
        - user
      summary: Update Current logged-in user info
      description: Return updated user info with preference/setting
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: header
          name: Authorization
          type: string
          required: true
      responses:
        "200":
          description: On success
          schema:
            type: object
            required:
              - code
              - message
            properties:
              code:
                type: integer
                format: int32
                example: 0
              message:
                type: string
                example: success
              data:
                $ref: "#/definitions/User"

definitions:
  User:
    type: object
    required: [id]
    properties:
      id:
        type: string
      name:
        type: string
      avatar:
        type: string
      pushToken:
        type: string
      phone:
        type: string
      email:
        type: string
      isEmailVerified:
        type: boolean
      gender:
        type: string
        enum:
          - Male
          - Female
          - Other
      preferences:
        $ref: "#/definitions/Preference"
  Preference:
    type: object
    properties:
      pushNotiEnabled:
        type: boolean
      collectAndUsePersonalInfo:
        type: boolean