server:
  port: 10081

spring:
  application:
    name: noljanolja-consumer
  profiles:
    include: management, redis, rsocket, firebase, storage
springdoc:
  swagger-ui:
    url: /swagger.yaml
  cache:
    disabled: false