spring:
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    connect-timeout: PT0.3S
    timeout: PT0.3S
    lettuce:
      pool:
        max-active: 20
        maxWait: PT1S
        max-idle: 20
        min-idle: 10
        time-between-eviction-runs: PT3S