server:
  port: 10082

spring:
  application:
    name: noljanolja-admin
  profiles:
    include: management, storage, firebase
springdoc:
  swagger-ui:
    url: /swagger.yaml
  cache:
    disabled: false