services:
  configs:
    - id: CORE
      baseUrl: ${CORE_BASE_URL}
    - id: AUTH
      baseUrl: ${AUTH_BASE_URL}
    - id: OPEN_AI
      baseUrl: ${OPEN_AI_BASE_URL}
      timeoutMillis: 60000
      extra:
        apiKey: ${OPEN_AI_API_KEY}
    - id: YOUTUBE
      baseUrl: ${YOUTUBE_BASE_URL}
      extra:
        apiKey: ${YOUTUBE_API_KEY}