package com.noljanolja.server.common.utils

const val REASON_SEND_MESSAGES = "REASON_SEND_MESSAGES"
const val REASON_REFERRAL_REWARD = "REASON_REFERRAL_REWARD"
const val REASON_DAILY_CHECKIN = "REASON_DAILY_CHECKIN"
const val REASON_PURCHASE_GIFT = "REASON_PURCHASE_GIFT"
const val REASON_WATCH_VIDEO = "REASON_WATCH_VIDEO"
const val REASON_LIKE_VIDEO = "REASON_LIKE_VIDEO"
const val REASON_COMMENT_VIDEO = "REASON_COMMENT_VIDEO"
const val REASON_EXCHANGE_POINT = "REASON_EXCHANGE_POINT"
const val REASON_SEND_POINT = "REASON_SEND_POINT"
const val REASON_RECEIVE_POINT = "REASON_RECEIVE_POINT"