openapi: 3.0.0
info:
  description: Public API for NoljaNolja consumer
  version: 1.0.2
  title: NoljaNolja Swagger
  contact:
    email: nguyenbrother9x@gmail.com
tags:
  - name: User
    description: Operation relate to current user
  - name: Conversation
    description: Operation relate to conversation in general
  - name: Push Token
    description: Operation relate to push token
  - name: Message
    description: Operation relate to message
  - name: Media
    description: Stickers, emojis, etc.
paths:
  /api/v1/users/me:
    get:
      tags: [User]
      summary: Get Current logged-in user info
      description: Return user info with preference/setting
      security:
        - bearerAuth: []
      responses:
        "200":
          description: On success
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/BaseResponse"
                  - type: object
                    properties:
                      data:
                        $ref: "#/components/schemas/User"
    put:
      tags: [User]
      summary: Update Current logged-in user info
      description: Return updated user info with preference/setting
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                gender:
                  type: string
                dob:
                  type: string
                preferences:
                  $ref: "#/components/schemas/UserPreference"
      responses:
        "200":
          description: On success
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/BaseResponse"
                  - type: object
                    properties:
                      data:
                        $ref: "#/components/schemas/User"
    post:
      tags: [User]
      summary: Update current user info using file
      description: Upload corresponding file to cloud, and update current user info if necessary. Return data related to uploaded file
      security:
        - bearerAuth: [ ]
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required: [field, files]
              properties:
                field:
                  type: string
                  enum: [AVATAR]
                files:
                  type: array
                  items:
                    type: string
                    format: binary
      responses:
        "200":
          description: On success
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/BaseResponse"
                  - type: object
                    properties:
                      data:
                        $ref: "#/components/schemas/UserFileUpload"
    delete:
      tags: [User]
      summary: Delete user
      description: This will remove user on both on firebase and noljanolja
      security:
        - bearerAuth: [ ]
      responses:
        "200":
          description: On success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BaseResponse"
  /api/v1/users/me/contacts:
    post:
      tags: [User]
      summary: Sync contact list
      description: This will sync data from user contact list to user friend list in server
      security:
        - bearerAuth: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [ contacts ]
              properties:
                contacts:
                  type: array
                  items:
                    $ref: "#/components/schemas/LocalContact"
      responses:
        "200":
          description: On success
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/BaseResponse"
                  - type: object
                    properties:
                      data:
                        type: array
                        items:
                          $ref: "#/components/schemas/User"
  /api/v1/push-tokens:
    post:
      tags: [ Push Token ]
      summary: Update push token
      description: Register a push token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [ userId, deviceToken, deviceType ]
              properties:
                userId:
                  type: string
                deviceToken:
                  type: string
                deviceType:
                  type: string
      responses:
        "200":
          description: on Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BaseResponse"
  /api/v1/conversations:
    get:
      tags: [Conversation]
      summary: Get list of conversation of current user
      description: Include recent participants and sender
      security:
        - bearerAuth: [ ]
      responses:
        "200":
          description: On success
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/BaseResponse"
                  - type: object
                    properties:
                      data:
                        type: array
                        items:
                          $ref: "#/components/schemas/Conversation"
    post:
      tags: [ Conversation ]
      summary: Create a conversation
      description: Include participants, and return created conversation
      security:
        - bearerAuth: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [title, participantIds, type]
              properties:
                title:
                  type: string
                participantIds:
                  type: array
                  items:
                    type: string
                type:
                  $ref: "#/components/schemas/ConversationType"
      responses:
        "200":
          description: On success
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/BaseResponse"
                  - type: object
                    properties:
                      data:
                        $ref: "#/components/schemas/Conversation"
  /api/v1/conversations/{conversationId}:
    get:
      tags: [Conversation]
      summary: Get conversation detail
      description: Include all participants, and many recent messages
      security:
        - bearerAuth: [ ]
      parameters:
        - in: path
          name: conversationId
          schema:
            type: number
          description: the id of the conversation
      responses:
        "200":
          description: On success
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/BaseResponse"
                  - type: object
                    properties:
                      data:
                        $ref: "#/components/schemas/Conversation"
  /api/v1/conversations/{conversationId}/messages:
    get:
      tags: [ Message ]
      summary: Get conversation's messages
      description: Return conversation messages with filter. Currently, maximum amount of messages returned are 20 per batch
      security:
        - bearerAuth: [ ]
      parameters:
        - in: path
          name: conversationId
          schema:
            type: number
          description: the id of the conversation
        - in: query
          name: beforeMessageId
          schema:
            type: number
          description: filter messages that were created before provided messageId
        - in: query
          name: afterMessageId
          schema:
            type: number
          description: filter messages that were created after provided messageId
      responses:
        "200":
          description: On success
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/BaseResponse"
                  - type: object
                    properties:
                      data:
                        $ref: "#/components/schemas/Conversation"
    post:
      tags: [ Message ]
      summary: Send a message/chat
      description: Add a message to a conversation and update last sender status
      security:
        - bearerAuth: [ ]
      parameters:
        - in: path
          name: conversationId
          schema:
            type: number
          description: the id of the conversation
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required: [message, type]
              properties:
                message:
                  type: string
                  description: | 
                    The content of the message. Format varies depending on the type.  
                    Examples:
                    - PLAINTEXT: Hi this is a message
                    - STICKER: 3/01.png {stickerPackId}/{stickerFileName}
                type:
                  $ref: "#/components/schemas/MessageType"
                attachments:
                  type: array
                  items:
                    type: string
                    format: binary
      responses:
        "200":
          description: On success
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/BaseResponse"
                  - type: object
                    properties:
                      data:
                        type: array
                        items:
                          $ref: "#/components/schemas/Message"
  /api/v1/conversations/{conversationId}/messages/{messageId}/seen:
    post:
      tags: [ Message ]
      summary: Seen a message
      description: Seen a message
      security:
        - bearerAuth: [ ]
      parameters:
        - in: path
          name: conversationId
          schema:
            type: number
          description: the id of the conversation
        - in: path
          name: messageId
          schema:
            type: number
          description: the id of the message
      responses:
        "200":
          description: On success
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/BaseResponse"
  /api/v1/conversations/{conversationId}/attachments/{attachmentId}:
    get:
      tags: [ Conversation ]
      summary: Download attachment
      description: Download attachment
      security:
        - bearerAuth: [ ]
      responses:
        "200":
          description: Return a file
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
  /api/v1/media/sticker-packs:
    get:
      tags: [Media]
      summary: Retrieve sticker packs of current user
      description: Currently retrieve all available sticker packs
      security:
        - bearerAuth: [ ]
      responses:
        "200":
          description: On success
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/BaseResponse"
                  - type: object
                    properties:
                      data:
                        type: array
                        items:
                          $ref: "#/components/schemas/StickerPack"
  /api/v1/media/sticker-packs/{stickerPackId}:
    get:
      tags: [ Media ]
      summary: Retrieve sticker pack
      description: This will trigger download of a zip file
      security:
        - bearerAuth: [ ]
      parameters:
        - in: path
          name: stickerPackId
          schema:
            type: number
          description: the id of the sticker pack
      responses:
        "200":
          description: On success, download a zip file with name `stickerPackId`.zip. The zip file will include a tray image, all sticker images, and a content.json metadata file for this sticker pack

  /api/v1/media/sticker-packs/{stickerPackId}/{stickerFile}:
    get:
      tags: [ Media ]
      summary: Retrieve a sticker image
      description: This will trigger download an image file with extension depend on the provided name
      security:
        - bearerAuth: [ ]
      parameters:
        - in: path
          name: stickerPackId
          schema:
            type: number
          description: the id of the sticker pack
        - in: path
          name: stickerFile
          schema:
            type: string
          description: the file name of the sticker
          example: 01_Hi.webp
      responses:
        "200":
          description: On success, this should trigger a download
components:
  securitySchemes:
    bearerAuth: # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Token from firebase (do not put 'bearer' in here)
      name: Bearer Token
  schemas:
    BaseResponse:
      type: object
      required: [code, message]
      properties:
        code:
          type: integer
        message:
          type: string
    User:
      type: object
      required: [id]
      properties:
        id:
          type: string
        name:
          type: string
        avatar:
          type: string
        pushToken:
          type: string
        phone:
          type: string
        email:
          type: string
        isEmailVerified:
          type: boolean
        dob:
          type: string
          description: in date format
          example: 2023-03-10 04:04:43
        gender:
          $ref: "#/components/schemas/Gender"
        preferences:
          $ref: "#/components/schemas/UserPreference"
        createdAt:
          type: string
          description: in date format
          example: 2023-03-10 04:04:43
        updatedAt:
          type: string
          description: in date format
          example: 2023-03-10 04:04:43
    UserPreference:
      type: object
      properties:
        collectAndUsePersonalInfo:
          type: boolean
    LocalContact:
      type: object
      properties:
        name:
          type: string
        emails:
          type: array
          items:
            type: string
        phones:
          type: array
          items:
            type: string
    Gender:
      type: string
      enum: [ MALE, FEMALE, OTHER ]
    UserFileUpload:
      type: object
      properties:
        path:
          type: string
        size:
          type: number
        md5:
          type: string
    ConversationType:
      type: string
      enum: [ SINGLE, GROUP ]
    Conversation:
      type: object
      properties:
        id:
          type: number
        title:
          type: string
        creator:
          $ref: "#/components/schemas/User"
        type:
          $ref: "#/components/schemas/ConversationType"
        messages:
          type: array
          items:
            $ref: "#/components/schemas/Message"
        participants:
          type: array
          items:
            $ref: "#/components/schemas/User"
        createdAt:
          type: string
        updatedAt:
          type: string
    Message:
      type: object
      properties:
        id:
          type: number
        conversationId:
          type: number
        message:
          type: string
        sender:
          $ref: "#/components/schemas/User"
        type:
          $ref: "#/components/schemas/MessageType"
        seenBy:
          type: array
          items:
            type: string
        attachments:
          type: array
          items:
            $ref: "#/components/schemas/Attachment"
        createdAt:
          type: string
    MessageType:
      type: string
      enum: [ PLAINTEXT, STICKER, GIF, PHOTO, DOCUMENT ]
    Attachment:
      type: object
      properties:
        id:
          type: number
        messageId:
          type: number
        name:
          type: string
          description: Server assign a unique name for each attachment
        originalName:
          type: string
          description: Original name of the file
        size:
          type: number
          description: Size of the file in bytes
        type:
          type: string
          description: Type of the file
          example: image/jpeg
        md5:
          type: string
    StickerPack:
      type: object
      properties:
        id:
          type: number
        name:
          type: string
        publisher:
          type: string
        trayImageFile:
          type: string
          description: the preview image of all the sticker
        isAnimated:
          type: boolean
          description: whether this sticker is animated
        stickers:
          type: array
          items:
            $ref: "#/components/schemas/Sticker"
    Sticker:
      type: object
      properties:
        image_file:
          type: string
          description: name of the sticker image file
        emojis:
          type: array
          items:
            type: string
            description: All emojis that this sticker will represent